export const groups = [
	{ animal: 'Avestruz', key: '1' },
	{ animal: 'Águia', key: '2' },
	{ animal: 'Burro', key: '3' },
	{ animal: 'Borboleta', key: '4' },
	{ animal: 'Cachorro', key: '5' },
	{ animal: 'Cabra', key: '6' },
	{ animal: 'Carneiro', key: '7' },
	{ animal: 'Camelo', key: '8' },
	{ animal: 'Cobra', key: '9' },
	{ animal: 'Coelho', key: '10' },
	{ animal: 'Cavalo', key: '11' },
	{ animal: 'Elefante', key: '12' },
	{ animal: 'Galo', key: '13' },
	{ animal: 'Gato', key: '14' },
	{ animal: 'Jacaré', key: '15' },
	{ animal: 'Leão', key: '16' },
	{ animal: 'Macaco', key: '17' },
	{ animal: 'Porco', key: '18' },
	{ animal: 'Pavão', key: '19' },
	{ animal: 'Peru', key: '20' },
	{ animal: 'Touro', key: '21' },
	{ animal: 'Tigre', key: '22' },
	{ animal: 'Urso', key: '23' },
	{ animal: 'Veado', key: '24' },
	{ animal: 'Vaca', key: '25' },
]
