# Generated by Django 4.2.5 on 2023-11-26 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_user_date_joined_user_is_active_user_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
